### ISSUE TITLE
Bug if structure pin names contain an underscore

### ISSUE THREAD

**Issue by JeromBaas** [mpasson/lekkersim#1]
If the basenames of the pins in a structure contain an underscore, for example 'opt_0', lekkersim will erroneously consider the basename to be 'opt', and therefore it will not find the connections to this structure.

**Comment by mpasson** [comment]
from 3e59f40988120aa78c273ac43a2e1139cd24ba58 internal reference to pins have been updated from strings to Pin objects, which keeps tracks of the base name and mode name separately.

Most input and output routines are kept the same (e.g. get_data), namely they still accept string. In that case, the name is still '{basename}_{modename}', but both sub names can have any character in them.
